__default__:
  jobname: "default"
  mem: "16G"
  cpus: 4
  time: "48:00:00"

bwa_mem:
  jobname: "bwa_mem"
  mem: "16G"
  cpus: 4
  time: "1:00:00"
  
samtools_sort:
  jobname: "samtools_sort"
  mem: "4G"
  cpus: 1
  time: "1:00:00"

samtools_index:
  jobname: "samtools_index"
  mem: "4G"
  cpus: 1
  time: "1:00:00"
  
samtools_mpileup:
  jobname: "samtools_mpileup"
  mem: "4G"
  cpus: 1
  time: "1:00:00"
  
bcftools_call:
  jobname: "bcftools_call"
  mem: "4G"
  cpus: 1
  time: "1:00:00"
  
plot_quals:
  jobname: "plot_quals"
  mem: "4G"
  cpus: 1
  time: "1:00:00"
  